// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type GetTeacherResultsRequest = Record<string, unknown>;

export type GetTeacherResultsResponse = {
  sessions?: Array<{
  answers?: Array<{
  answer_json?: string;
  answered_at?: string;
  is_correct?: boolean;
  points_earned?: number;
  question_id?: number;
}>;
  completed_at?: string | null;
  id?: number;
  max_score?: number;
  phase_scores?: Record<string, unknown>;
  started_at?: string;
  student_name?: string;
  total_score?: number;
}>;
  total_students?: number;
};

export type SaveStudentAnswerRequest = {
  answer_json?: string;
  is_correct?: boolean;
  points_earned?: number;
  question_id: number;
  session_id: number;
};

export type SaveStudentAnswerResponse = {
  ok?: boolean;
};

export type SaveStudentSessionRequest = {
  completed?: boolean;
  max_score?: number;
  phase_scores?: string;
  session_id?: number | null;
  student_name?: string;
  total_score?: number;
};

export type SaveStudentSessionResponse = {
  ok?: boolean;
  session_id?: number;
};

export class Space {
  static getTeacherResults(request: GetTeacherResultsRequest): Promise<GetTeacherResultsResponse> {
    return executeAction<GetTeacherResultsResponse>("get_teacher_results", request);
  }

  static getTeacherResultsStream(request: GetTeacherResultsRequest): AsyncIterable<GetTeacherResultsResponse> {
    return executeActionStream<GetTeacherResultsResponse>("get_teacher_results", request);
  }

  static saveStudentAnswer(request: SaveStudentAnswerRequest): Promise<SaveStudentAnswerResponse> {
    return executeAction<SaveStudentAnswerResponse>("save_student_answer", request);
  }

  static saveStudentAnswerStream(request: SaveStudentAnswerRequest): AsyncIterable<SaveStudentAnswerResponse> {
    return executeActionStream<SaveStudentAnswerResponse>("save_student_answer", request);
  }

  static saveStudentSession(request: SaveStudentSessionRequest): Promise<SaveStudentSessionResponse> {
    return executeAction<SaveStudentSessionResponse>("save_student_session", request);
  }

  static saveStudentSessionStream(request: SaveStudentSessionRequest): AsyncIterable<SaveStudentSessionResponse> {
    return executeActionStream<SaveStudentSessionResponse>("save_student_session", request);
  }

}
